server:
  port: 8090
  servlet:
    context-path: /demo
spring:
  jackson:
    time-zone: GMT+8
  mvc:
    view:
      prefix: /view/
      suffix: .html
    static-path-pattern: /*
  resources:
    static-locations: classpath:/static/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xmr.dome.domain
logging:
  config: classpath:logback-boot.xml

