server:
  port: 8090
  servlet:
    context-path: /demo
spring:
  jackson:
    time-zone: GMT+8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 30
        max-wait: 1000ms
        max-idle: 30
        min-idle: 0
    timeout: 5000ms
  mvc:
    view:
      prefix: /view/
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xmr.dome.domain
logging:
  config: classpath:logback-boot.xml

