spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cy?serverTimezone=UTC
    username: root
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 5000ms
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xmr.dome.domain
logging:
  config: classpath:logback-boot.xml

ali_return_url: https://127.0.0.1/alipay/getReturnUrlInfo
ali_notify_url: https://127.0.0.1/alipay/getNotifyUrlInfo
product_code: FAST_INSTANT_TRADE_PAY
timeout_express: 15m
url: https://openapi.alipaydev.com/gateway.do
appid: 2016092200570983
private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCWGRC83ernd7DyPovalsUpIxgmfmda8l6js6W772V2XJp+mieHWF4lPbpNp0p/jfX1Kp7x1PEOWVaRBklHBVsoWwb0PJYknsi/HUwjyACW8LDM04gsjuKDyIVvYcdzMZsUiR9unlQsy1IGmQQY7fJRu8W3Vj/yJezpZ7zG8HybkE3W9JBMTeOK4kM0Du5RjdJ7I5RM+wCtYVdcb/sVj7FHWBrPrsbWcecv+827Wd61S7V4ltfClTIGj5SuNL2+LW/GnrtS86el4xmuYidiOoLd4U4qKbiLV4D1+SXE5jBbd26eFw4VBsYRRaqB2T0XwaGJEJEO8cHXmiFU/oTbXVTVAgMBAAECggEADHDXalAagETzbaCxhtSoUtiNz+L6PheIsJjbS9Bz4HOcepHcZON2KjALmRQcoKXrlP6LXhAASugsvKiAulo/TAD/eo7rAu4GRZDwFqclJV2dydxelRLiw3mDVdAM8AdUi0cyS8DjyTKxAcr9A/P0+cFOifukITXzhQUMKJEWQu56hnEChSBJQvZitEg10GNQcleEAEsCZoiVsMbamRsPXoo5yJM0GAtJVy8K4ncEZVKzS4Xj/NAO5TMua9rDVSqi0qqKeqi47MPgUPJvSdqJZIrmXW+sqIhyk9NtGC0f47WQX0SDsvgMPfEhSj97gO419P8vQzZfPZSCcUg+9i5nAQKBgQDEUBab8+xxYVPFzX+SvSle4lNwamjuF3fpiFFWTV1hkRTrKGbgzDo+3lTk1ydeVHf50LXz/3YQbAs/EEAisoDZabePVSWKL5PkEc+d+kGfyUEHMjF9ar/4EgsihctAaQXPQja9Dysx6alRWlmQ5KvCy2S/OZcq0ixmWjzruT3reQKBgQDDu9xmq/KtM8C+gA9yjMx4m9S+GOipUqkivIess5INqDzC8DBNkZk94ahSAqWMPQ1jhAFWQBpupVpQYlRohw6dRshj7E+kjjZ2nBDUO2Wxu9KpWzg5/IivJT/Io0oP9HLwMQrHz2O40iZgKJfogQx/M9CRP8lR1uC40kmxVkbBPQKBgC3lc4O+gXb4hDdolfzekL+INm2/0wxnHDfTEQEWUVCwNK3N4k+IL83m+P4PdzrMkMgtDX0gKqAoQnDaAcSa6xjpaGrwQziNawwVRe7vRUxwJu3hxERIIt2Cimvlz+EdLKiKGHYXB8hBkr5cWzhO3gFKwCEc+8SdIphDXJ7XziwxAoGAfM7ESh+oXXLbm11S/Er1co6DCDgf2yAfQ0wOAzx5jAXTwMWhN0T4/vFt/+U6JIMlj2gz5gh4EkeToCAjDIfZ9MWWr8iWPCqGZfk77eh1/u/x8xV8c9UoXu4Ujt44MpY/2BKdei0uvEIcQEKCIrpu+olSm9udhnbK0m8cmFyYP00CgYEAheNN7tzZXsi6y1lt1wLB22DkYCeydv1r6zPMc1m8UOmHBE0fRltj1CLer+mx1opGALIkmk2JiaoPm1kDVyuLWtWu6NVaVXd4PQNeMSRi3T47WgwyRwLkInu1HxM4vWPFHl0dkvq7rPGpVQJ/H24Mn7mb6CxqLjdnPAcBe+Q9yDE=
ali_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0fXo73p0PHMlbO9W2SEGWQ3BhgukPWqpnk/bOE5cKtIiS1oKd1y6om2WYPt5Sbgfn0uRhfI6GCkUSQKKSD9DbDs82MZlHfmdvF3NXTFIjX0pWXKItkmYJ2lR8JAWmZoK5jMzbTyQiqaAVLAnagZcIWoZH9290dkcXXv4uCCZwcgFr1qpT85l+jbfhNcnAaAPISIHNbf6eRa5g30KzRjyVzwXBvgiXVVTZInv8XR4wlpnPHHIPHsLWT/yL5g9GomzFi1cmY3Tzvmx3eRDOtqd73qWW9eA9tnXgdZiZow+RQnStQ4rCGZsN2JoIreQy1nnxN1blL/JoUgsSm9hLzcTYwIDAQAB
sign_type: RSA2
